### ISSUE TITLE
403 Client Error while executing the code

### ISSUE THREAD

**Issue by pankajmitsom** [backtrackbaba/cowin#8]
403 Client Error: Forbidden for url: https://cdn-api.co-vin.in/api/v2/admin/location/states while executing the below code what needs to be done here, please guide.

from cowin_api import CoWinAPI

cowin = CoWinAPI()

states = cowin.get_states()
print(states)

**Comment by DragonWarrior15** [comment]
Hey, I tried running this just now on my system and it works fine. I suggest you do the following checks
* Try restarting the terminal and run these set of commands
* Check if the system is behind any VPN or proxy that is preventing python from connecting to the URL (In my experience, I have faced problems with python connecting to certain sites behind a proxy, and VPN may give the error since the API might prevent anyone from outside India to connect)
* You can also try to run the commands on a colab notebook for the purpose of doing these checks

**Comment by backtrackbaba** [comment]
@pankajmitsom I tried running and it worked fine. Also had a word with a few people who use this project and they didn't face any issue with fetching the states.

If you cross the rate limit of 100 requests every 5 mins, you might be temporarily banned by CoWin.

Hope this helps!

**Comment by backtrackbaba** [comment]
@pankajmitsom Closing the issue for now. Let us know if it persists
